#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! [ -x "$(command -v pnpm)" ];
then
    exe="npm"
else
    exe="pnpm"
fi

# format and maybe lint files
$exe run fix

# Add only the edited staged files again to staged, ignore modified but unstaged files
git update-index --again

exit 0
