name: ci
on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install Packages
              run: npm install

            - name: Code Quality
              run: npx rome ci .

            - name: Build Files
              run: npm run build