name: ci
on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install packages
              run: pnpm install

            # - name: Code Quality
            #   run: pnpm rome ci .

            - name: Build Files
              run: pnpm build
